site_name: TS-VIS
# Repository
repo_name: Github
repo_url: https://github.com/iGame-Lab/zjvis
edit_uri: "blob/master/docs/"

# Copyright
copyright: Copyright &copy; 2021 <a href="http://igame.hdu.edu.cn/" target="_blank">iGame</a> & <a href="https://www.zhejianglab.com/"  target="_blank">Zhejiang Lab</a> <br/> TS-VIS 由杭州电子科技大学智能可视建模与仿真实验室(iGame Lab)和之江实验室(Zhejiang Lab)联合开发

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - content.tabs.link
  palette:
    scheme: default
    primary: indigo
    accent: indigo

extra_css:
  - assets/css/simpleLightbox.min.css
  - assets/css/lightbox.css

extra_javascript:
  - https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js
  - assets/js/simpleLightbox.min.js
  - assets/js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# Extensions
markdown_extensions:
  - markdown.extensions.attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

nav:
    - 首页: index.md

    - 快速使用:
      - 安装: quick_start/install.md
      - 快速上手: quick_start/quickstart.md
      - 启动可视化并在浏览器中查看: quick_start/run_visual.md

    - 可视化日志写入:
      - 模型结构: write_log/write_graph.md
      - 标量数据: write_log/write_scalar.md
      - 媒体数据: write_log/write_media.md
      - 统计分析数据: write_log/write_statistic.md
      - 降维分析数据: write_log/write_embedding.md
      - 超参数: write_log/write_hyperparm.md
      - 异常检测数据: write_log/write_exception.md

    - 使用可视化组件:
      - 主界面:   use_visualization/overall.md
      - 模型结构: use_visualization/graph.md
      - 标量数据: use_visualization/scalar.md
      - 媒体数据: use_visualization/media.md
      - 统计分析: use_visualization/statistic.md
      - 降维分析: use_visualization/embedding.md
      - 超参分析: use_visualization/hyperparm.md
      - 异常检测: use_visualization/exception.md
      - 用户定制: use_visualization/custom.md

    - 开发者文档:
      - 后端请求API: developer/api.md
      - 可视化前端: developer/frontend.md
      - 可视化后端启动选项: developer/commandline_for_backend.md
      - 更新记录: developer/changelog.md
      - 参与贡献: developer/contribute.md

    - 开源软件许可:
      - 开源软件: thanks/license.md
